//Error Types
export const GET_ERRORS = "GET_ERRORS";

//User Types
export const SET_CURRENT_USER = "SET_CURRENT_USER";


//Maison Types
export const GET_SIMPLE_SAVED_MAISONS = "GET_SIMPLE_SAVED_MAISONS";
export const NEW_SIMPLE_ESTIMATION_MAISON = "NEW_SIMPLE_ESTIMATION_MAISON";
export const DELETE_SIMPLE_SAVED_MAISON = "DELETE_SIMPLE_SAVED_MAISON";

//Appartement Types
export const GET_SIMPLE_SAVED_APPARTEMENTS = "GET_SIMPLE_SAVED_APPARTEMENTS";
export const NEW_SIMPLE_ESTIMATION_APPARTEMENT = "NEW_SIMPLE_ESTIMATION_APPARTEMENT";
export const DELETE_SIMPLE_SAVED_APPARTEMENT = "DELETE_SIMPLE_SAVED_APPARTEMENT";


//User Types
export const SET_USER_TYPE_TO_SUPER = "SET_USER_TYPE_TO_SUPER";